### ISSUE TITLE
编译提示找不到chem.mod

### ISSUE THREAD

**Issue by SKT-Bush** [OpenCFD-IMECH/OpenCFD-Comb#1]
尊敬的维护者，你好。
我今天尝试编译Opencfd-comb的时候屡次出现找不到chem.mod的报错，但是Opencfd-SC可以正常编译，请问是什么原因呢？
![error](https://github.com/OpenCFD-IMECH/OpenCFD-Comb/assets/46962138/e91d1786-ded2-48c9-8475-50056d726a7e)

**Comment by FR13ndSDP** [comment]
> 编译顺序问题，module编译应该早于其他代码，你可以试一下最新的代码是否已经解决了此问题

[update](https://github.com/OpenCFD-IMECH/OpenCFD-Comb/commit/a008543b06f9e74a04e1e2e510cd8d0e13f0e88c)
